### ISSUE TITLE
L_03 gives a transformation error when uploading

### ISSUE THREAD

**Issue by ingenieroariel** [ethgis/ethnode#2]
` java.io.IOException: transform error`

Full exception seems to be related to the bounding box.

```
Caused by: java.io.IOException: transform error
	at org.geoserver.catalog.CatalogBuilder.getLatLonBounds(CatalogBuilder.java:572)
	at org.geoserver.catalog.CatalogBuilder.doSetupBounds(CatalogBuilder.java:513)
	at org.geoserver.catalog.CatalogBuilder.setupBounds(CatalogBuilder.java:497)
	at org.geoserver.rest.catalog.DataStoreFileController.dataStorePut(DataStoreFileController.java:493)
	... 108 more
Caused by: org.geotools.referencing.operation.projection.ProjectionException: Transformation doesn't convergence.
	at org.geotools.referencing.operation.projection.MapProjection.inv_mlfn(MapProjection.java:1399)
	at org.geotools.referencing.operation.projection.TransverseMercator.inverseTransformNormalized(TransverseMercator.java:217)
```

**Comment by ingenieroariel** [comment]
The projection indicates the following parameters:

```
PROJCS["WGS_1984_UTM_Zone_37N",
    GEOGCS["GCS_WGS_1984",
        DATUM["WGS_1984",
            SPHEROID["WGS_84",6378137,298.257223563]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",39],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["Meter",1]]
```

**Comment by ingenieroariel** [comment]
I am trying to fix things by switching to a proper EPSG code projection:

https://epsg.io/32637

```
PROJCS["WGS 84 / UTM zone 37N",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",39],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32637"]]
```

**Comment by ingenieroariel** [comment]
Creating a new dataset using ogr2ogr from the gdal-bin package on Ubuntu:

```
ogr2ogr -t_srs EPSG:32637 Lo_03_23637.shp Lo_03.shp
```

Resulted in a new error when uploading:

<img width="446" alt="screen shot 2017-11-09 at 2 06 21 am" src="https://user-images.githubusercontent.com/54999/32592658-c52bcc74-c4f2-11e7-823d-e30436426199.png">

**Comment by ingenieroariel** [comment]
Changing to 4326 in the command line pointed to a potential problem in a particular feature:

```
ogr2ogr -t_srs EPSG:4326 Lo_03_4326.shp Lo_03.shp
Failed to reproject feature 4644 (geometry probably out of source or destination SRS).
```

**Comment by ingenieroariel** [comment]
```
Failed to reproject feature 4644 (geometry probably out of source or destination SRS).
Failed to reproject feature 42381 (geometry probably out of source or destination SRS).
```

**Comment by ingenieroariel** [comment]
```
ogr2ogr -t_srs EPSG:4326 Lo_03_4326.shp Lo_03.shp -skipfailures
ogr2ogr -t_srs EPSG:32637 Lo_03_32637.shp Lo_03_4326.shp
```

Gave us success:

<img width="813" alt="screen shot 2017-11-09 at 2 12 38 am" src="https://user-images.githubusercontent.com/54999/32592865-94c7ddb0-c4f3-11e7-960c-b5a87bd32ec7.png">

**Comment by ingenieroariel** [comment]
The problematic points are here (shown with the previous and next for context:


# 4644

```
OGRFeature(Lo_03):4643
  ID (Integer) = 0
  LO_NAME (String) = Yedeldey
  LO_CODE (Integer) = 1
  POINT (521797.612646192603279 1294247.277066525770351)

OGRFeature(Lo_03):4644
  ID (Integer) = 0
  LO_NAME (String) = (null)
  LO_CODE (Integer) = 1
  POINT (too_big too_big)

OGRFeature(Lo_03):4645
  ID (Integer) = 0
  LO_NAME (String) = Mehal zeng
  LO_CODE (Integer) = 1
  POINT (530162.717060797498561 1303412.563836330082268)
```

and

# 42380
```
OGRFeature(Lo_03):42380
  ID (Integer) = 0
  LO_NAME (String) = Molisa
  LO_CODE (Integer) = 1
  POINT (357341.079318406817038 1181448.345231229439378)

OGRFeature(Lo_03):42381
  ID (Integer) = 0
  LO_NAME (String) = (null)
  LO_CODE (Integer) = 1
  POINT (too_big too_big)

OGRFeature(Lo_03):42382
  ID (Integer) = 0
  LO_NAME (String) = Chefe
  LO_CODE (Integer) = 1
  POINT (508431.307742962497286 1084199.90435034618713)
```
